-- Task 2 -- 

-- query 1 - list of all the customers
select * from user;

-- query 2 - list all orders for a specific customer
select o.user_id,o.courier_id , c.sender_name, c.reciever_name, c.tracking_number, c.delivery_date, c.status 
from courier_management.order o join courier_management.courier c on o.courier_id = c.id join courier_management.user u on o.user_id = u.id 
where u.name in (select name  from user);

-- query 3 - list all couriers
select * from courier;

-- query 4 - list all packages for specific courier 
# couldn't understand the question looks similar to query 2
-- query 5 list all delevireies for a specific courier
# couldn't understand the question looks similar to query 2

-- query 6 list all undelivered packages
select * from courier 
where status <> 'Delivered';

-- query 7 list all packages that are schedules for delivery today 
select * from courier
where delivery_date = curdate();

-- query 8 lsit all packages with a specific status
select * from courier
where status = 'Delivered';

-- query 9 caluate the  total number of packages for each courier
select sender_name, count(id) as total_packages
from courier 
group by sender_name;

-- query 10 find the average delivery time for each courier
select c.sender_name,avg(DATEDIFF(p.payment_date, c.delivery_date)) as average_delivery_time
from courier c join payment p ON c.id = p.courier_id;

-- query 11 lsit all packages with a specific weight range
select * from courier where weight < 4;

-- query 12 retrieve emoployees whose names contain 'john'
select * from employee where name = 'john';

-- query 13 retrieve all courier records with payment greater than 50
select c.* 
from courier c join payment p on c.id = p.courier_id
where p.amount > 50;

-- Task 3 ---

-- Query 14 find the total number of couriers handled by each employee

select e.id, e.name, count(c.id)
from employee e left join location l on l.employee_id = e.id left join payment p on p.location_id = l.id 
left join courier c on c.id = p.courier_id
group by e.id;
 
-- Query 15 calculate the total revenue  generated by each location

select l.id ,l.name,sum(p.amount)
from location l join payment  p on p.location_id = l.id
group by l.id;

-- Query 16 find the total number of couriers delivered to each location 
		
select l.name AS location_name, COUNT(c.id) as total_couriers_delivered
from location l left join  payment p on l.id = p.location.id
left join courier c on p.courier_id = c.id
where c.status = 'Delivered'
group by l.id;

-- Query 17 find the courier with the highest average delivery time 

select c.id, avg(datediff(c.delivery_date, p.payment_date)) as avg_delivery_time
from courier c join payment p on c.id = p.courier_id
group by c.id
order by avg_delivery_time desc
limit 1;

-- Query 18 find locations with total payments less than a certain mmount

select l.name as location_name, sum(p.amount) as total_payment
from location left join payment p on l.id = p.location_id
GROUP BY l.id
having total_payment < 400;

-- Query 19 calculate the total payments per location 

select l.id ,l.name,sum(p.amount)
from location l join payment  p on p.location_id = l.id
group by l.id;

-- Query 20 retrieve couriers who have received payments totaling more than $1000 in a specific location (locationid = x)

select c.id, c.sender_name, c.reciever_name, sum(p.amount) AS total_payment
from courier c join payment p on c.id = p.courier_id
where p.location_id = 1
group by c.id
having total_payment > 50;

-- query 21 Retrieve couriers who have received payments totaling more than $1000 after a certain date (PaymentDate > 'YYYY-MM-DD')

select c.id, c.sender_name, c.reciever_name, sum(p.amount) as total_payment,p.payment_date
from courier c join payment p on c.id = p.courier_id
where p.payment_date > '2024-03-10'
group by c.id
having total_payment > 50;

-- query 22 retrieve locations where the total amount received is more than $5000 before a certain date (PaymentDate > 'YYYY-MM-DD')

select l.id ,l.name as location_name, sum(p.amount) as total_payment
from location l join payment p on l.id = p.location_id
where p.payment_date > '2024-03-10'
group by l.id
having total_payment > 100;

-- query 23 retrieve payments with courier information

select p.*, c.*
from payment p
join courier c on p.courier_id = c.id;

-- query 24 retrieve payments with location information

select p.*, l.*
from payment p
join location l on p.location_id = l.id;

-- query 25 retrieve payments with courier and location information 

select p.*, c.*, l.*
from payment p
join courier c on p.courier_id = c.id
join location l on p.location_id = l.id;

-- query 26 list all payments with courier details

select  p.*, c.*
from payment p
join courier c on p.courier_id = c.id;

-- query 27 Total payments received for each courier

select c.tracking_number, sum(p.amount) as total_payment_received
from courier c
left join payment p on c.id = p.courier_id
group by c.tracking_number;

-- query 28 list payments made on a specific date
select *
from payment
where payment_date = '2024-03-01';

-- query 29  get courier information for each payment

select p.*, c.*
from payment p
join courier c on p.courier_id = c.id;

-- query 30 get payment details with location

select p.*, l.*
from payment p
join location l on p.location_id = l.id;















 



	




